#!/bin/sh
cd ~/CreditcoinDocs-Mainnet/


# 1. Get signer 
OLDSIGNER=$(docker exec sawtooth-validator-default cat /etc/sawtooth/keys/validator.priv)

# 2. Client stop
docker-compose -f ./Client/creditcoin-client.yaml down

# 3. Change Key
cd ~/
docker exec sawtooth-validator-default sh -c "echo '35164e70c605b9b6fc14d76aa1133be5801af3c16822c93a8d3d7c62963787a5' > /etc/sawtooth/keys/validator.priv"
docker exec sawtooth-validator-default sh -c "echo '035d6297d864866a6c9db2bc2d177c8215424ecd27032f2bdbb2296f66c017ed91' > /etc/sawtooth/keys/validator.pub"

# 4. Get new signer & pub
## Creditcoin Miner must be on running status
## If you successfully terninated step1, It will fine.
cd ~/CreditcoinDocs-Mainnet/
NEWSIGNER=$(docker exec sawtooth-validator-default cat /etc/sawtooth/keys/validator.priv)
NEWPUBLIC=$(docker exec sawtooth-validator-default cat /etc/sawtooth/keys/validator.pub)

echo "new-signer: $NEWSIGNER"
echo "new-public: $NEWPUBLIC"

# 5. replace SIGNER
sed -i "s|$OLDSIGNER|$NEWSIGNER|g" ./Client/clientConfig.json

# 6. Run client
docker-compose -f ./Client/creditcoin-client.yaml up -d

# 7. Run client shell
docker exec -it creditcoin-client bash
