#!/bin/sh
cd ~/CreditcoinDockerCompose-Mainnet/


# 1. Get signer 
OLDSIGNER=$(docker exec sawtooth-validator-default cat /etc/sawtooth/keys/validator.priv)

# 2. Client stop
docker-compose -f ./Client/docker-compose.yaml down

# 3. Change Key
cd ~/
docker exec sawtooth-validator-default sh -c "echo ' ' > /etc/sawtooth/keys/validator.priv"
docker exec sawtooth-validator-default sh -c "echo ' ' > /etc/sawtooth/keys/validator.pub"

# 4. Get new signer & pub
## Creditcoin Miner must be on running status
## If you successfully terninated step1, It will fine.
cd ~/CreditcoinDockerCompose-Mainnet/
NEWSIGNER=$(docker exec sawtooth-validator-default cat /etc/sawtooth/keys/validator.priv)
NEWPUBLIC=$(docker exec sawtooth-validator-default cat /etc/sawtooth/keys/validator.pub)

echo "new-signer: $NEWSIGNER"
echo "new-public: $NEWPUBLIC"

# 5. replace SIGNER
sed -i "s|$OLDSIGNER|$NEWSIGNER|g" ./Client/clientConfig.json

# 6. Run client
docker-compose -f ./Client/docker-compose.yaml up -d

# 7. Run client shell
docker exec -it creditcoin-client bash
